"""Initial club schema

Revision ID: 70a2c9ef078c
Revises:
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "70a2c9ef078c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "club_notes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("short_name", sa.String(length=5), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("motto", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "players",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("nickname", sa.String(length=40), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("positions", sa.String(length=60), nullable=False),
        sa.Column("dominant_foot", sa.String(length=10), nullable=False),
        sa.Column("age_group", sa.String(length=12), nullable=False),
        sa.Column("photo_url", sa.String(length=500), nullable=False),
        sa.Column("contact_preference", sa.String(length=80), nullable=False),
        sa.Column("preferred_times", sa.String(length=200), nullable=False),
        sa.Column("availability", sa.String(length=20), nullable=False),
        sa.Column("injury_note", sa.String(length=300), nullable=False),
        sa.Column("skill", sa.Float(), nullable=False),
        sa.Column("jersey", sa.Integer(), nullable=False),
        sa.Column("is_captain", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("skill >= 1 AND skill <= 10"),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_players_team_id"), ["team_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('player', 'captain', 'admin')"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("player_id"),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=False),
        sa.Column("address", sa.String(length=250), nullable=False),
        sa.Column("pitch", sa.String(length=100), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=False),
        sa.Column("away_score", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("formation", sa.String(length=10), nullable=False),
        sa.Column("recurrence_id", sa.String(length=36), nullable=True),
        sa.Column("reminder_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.CheckConstraint("kind IN ('classic', 'mixed')"),
        sa.CheckConstraint("status IN ('scheduled', 'live', 'completed', 'cancelled')"),
        sa.CheckConstraint("home_score >= 0 AND away_score >= 0"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_matches_season_id"), ["season_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_matches_starts_at"), ["starts_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_matches_status"), ["status"], unique=False)

    op.create_table(
        "lineups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.CheckConstraint("side IN ('home', 'away')"),
        sa.CheckConstraint("slot >= 0 AND slot <= 10"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "player_id"),
        sa.UniqueConstraint("match_id", "side", "slot"),
    )
    with op.batch_alter_table("lineups", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_lineups_match_id"), ["match_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_lineups_player_id"), ["player_id"], unique=False)

    op.create_table(
        "match_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("assist_player_id", sa.Integer(), nullable=True),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("kind", sa.String(length=15), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('goal', 'own_goal', 'yellow_card', 'red_card')"),
        sa.CheckConstraint("side IN ('home', 'away')"),
        sa.ForeignKeyConstraint(
            ["assist_player_id"],
            ["players.id"],
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("match_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_match_events_match_id"), ["match_id"], unique=False)

    op.create_table(
        "ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.CheckConstraint("value >= 1 AND value <= 10"),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "player_id", "author_id"),
    )
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ratings_match_id"), ["match_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ratings_player_id"), ["player_id"], unique=False)

    op.create_table(
        "rsvps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('going', 'maybe', 'out')"),
        sa.ForeignKeyConstraint(["match_id"], ["matches.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("match_id", "player_id"),
    )
    with op.batch_alter_table("rsvps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rsvps_match_id"), ["match_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rsvps_player_id"), ["player_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("rsvps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rsvps_player_id"))
        batch_op.drop_index(batch_op.f("ix_rsvps_match_id"))

    op.drop_table("rsvps")
    with op.batch_alter_table("ratings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ratings_player_id"))
        batch_op.drop_index(batch_op.f("ix_ratings_match_id"))

    op.drop_table("ratings")
    with op.batch_alter_table("match_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_match_events_match_id"))

    op.drop_table("match_events")
    with op.batch_alter_table("lineups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lineups_player_id"))
        batch_op.drop_index(batch_op.f("ix_lineups_match_id"))

    op.drop_table("lineups")
    with op.batch_alter_table("matches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_matches_status"))
        batch_op.drop_index(batch_op.f("ix_matches_starts_at"))
        batch_op.drop_index(batch_op.f("ix_matches_season_id"))

    op.drop_table("matches")
    op.drop_table("users")
    with op.batch_alter_table("players", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_players_team_id"))

    op.drop_table("players")
    op.drop_table("teams")
    op.drop_table("seasons")
    op.drop_table("club_notes")
    # ### end Alembic commands ###
