"""Revocable member sessions

Revision ID: 950ea0f88807
Revises: 4e219eca7067
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "950ea0f88807"
down_revision: Union[str, None] = "4e219eca7067"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("session_version", sa.Integer(), server_default="1", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("session_version")

    # ### end Alembic commands ###
